version: ~> 1.0

language: scala
scala: [2.13.3]

before_install:
  - git fetch --tags

stages:
  - name: check
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - stage: check
      name: compile
      script: sbt Test/compile
    - stage: release
      script: sbt ci-release

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.sbt/launchers
