name: Build and Test
on:
  push:
    branches: [master]
  pull_request_target:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 10

      - name: Fetch tags
        run: |
          git fetch --depth=100 origin +refs/tags/*:refs/tags/*
          git log --oneline -10

      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9

      - name: Cache Coursier cache
        uses: coursier/cache-action@v5

      - name: scalafmt
        run: sbt --client scalafmtCheckAll

      - name: compile
        run: sbt --client Test/compile

      - name: test
        run: sbt --client test

      - name: sbt shutdown
        run: sbt --client shutdown
