name: Build and Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk-version: [1.8, 1.11]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Fetch tags
        run: git fetch --depth=100 origin +refs/tags/*:refs/tags/*

      - name: Set up JDK ${{ matrix.node }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk-version }}

      - name: Cache Coursier cache
        uses: coursier/cache-action@v5

      - name: sbt test
        run: sbt test
