name: Build and Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Fetch tags
        run: git fetch --depth=100 origin +refs/tags/*:refs/tags/*

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('project/build.properties') }}
          restore-keys: |
            sbt-${{ hashFiles('project/build.properties') }}
            sbt-

      - name: Cache Coursier cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/coursier
          key: coursier-${{ hashFiles('**/build.sbt', 'project/**') }}
          restore-keys: |
            coursier-${{ hashFiles('**/build.sbt', 'project/**') }}
            coursier-

      - name: sbt test
        run: sbt test
